In [1]:
import pandas as pd

In [2]:
def transform_countries_info(movies_data):
    """
    Принимает таблицу с колонкой «Страна производства» и добавляет к таблице 5 новых колонок:
    по одной на каждую отдельную страну. Значение в каждой из колонок соответствует тому,
    принимала ли конкретная страна участие в производстве фильма.
    
    Аргументы:
        movies_data: Исходная таблица с клонкой «Страна производства».
        
    Возвращаемое значение:
        Нет. Функция модифицирует переданную таблицу, но ничего не возвращает.
    """
    
    countries = ['Россия', 'Германия', 'США', 'Италия', 'Франция']
    new_columns = [[] for i in range(len(countries))]
    
    for _, row in movies_data.iterrows():
        country_of_origin_united = row['Страна производства']
        countries_of_origin = country_of_origin_united.split('-')
        
        for i in range(len(countries)):
            country = countries[i]
            
            if country in countries_of_origin:
                new_columns[i].append('Да')
            else:
                new_columns[i].append('Нет')
                
    for i in range(len(countries)):
        movies_data[countries[i]] = new_columns[i]

In [3]:
# В переменную movies_budget загружена таблица из файла movies_budget.csv
movies_budget = pd.read_csv('movies_budget.csv', sep=';')

res = movies_budget.groupby('Жанр фильма')['Число зрителей'].\
    sum().\
        sort_values(ascending=False).\
            reset_index()
res

      Жанр фильма  Число зрителей
0           Драма       144536483
1         Триллер        30519114
2          Боевик        20859969
3  Документальный        10093471
4         Комедия         9920914

In [4]:
transform_countries_info(movies_budget)
groups = movies_budget[movies_budget['Россия'] == "Да"].\
    groupby("Жанр фильма").\
        size().\
            sort_values(ascending=False).\
                reset_index().rename(columns={0: "Число фильмов"})

groups

      Жанр фильма  Число фильмов
0           Драма            123
1         Триллер            111
2          Боевик             77
3  Документальный             40
4         Комедия             33